dist: xenial

language: python

sudo: true

python:
  - 2.7
  - 3.6
  - 3.7-dev

before_install:
  - sudo apt-get install cython python-dev
  - pip install Cython
  - sudo apt-get install libmpfr-dev
  - sudo apt-get install libflint-dev
  - wget https://github.com/fredrik-johansson/arb/archive/2.16.0.tar.gz
  - mv 2.16.0.tar.gz arb-2.16.0.tar.gz
  - tar -xf arb-2.16.0.tar.gz
  - cd arb-2.16.0
  - ./configure --disable-static
  - make -j4
  - sudo make install
  - sudo ldconfig
  - cd ..

install:
  - pip install .

script:
  - python test/test.py
